# Copyright 2026 Therp BV <https://therp.nl>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
from odoo.fields import Command
from odoo.tests.common import TransactionCase

from odoo.addons.base.tests.common import DISABLED_MAIL_CONTEXT


class WorkAndLeavesBase(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.env = cls.env(context=dict(cls.env.context, **DISABLED_MAIL_CONTEXT))
        # Manager who approves leaves.
        cls.manager_user = cls.env["res.users"].create(
            {
                "name": "Test Manager",
                "login": "test_manager@example.com",
                "email": "test_manager@example.com",
                "groups_id": [
                    Command.link(
                        cls.env.ref("hr_holidays.group_hr_holidays_manager").id
                    )
                ],
            }
        )
        cls.manager = cls.env["hr.employee"].create(
            {
                "name": "Test Manager",
                "user_id": cls.manager_user.id,
            }
        )
        calendar = cls.env["resource.calendar"].create(
            {
                "name": "Test 5-day Calendar",
                "tz": "UTC",
            }
        )
        # Remove default attendances generated by Odoo, then add our own.
        calendar.attendance_ids.unlink()
        calendar.write(
            {
                "attendance_ids": [
                    Command.create(
                        {
                            "name": day_name,
                            "dayofweek": str(day_index),
                            "hour_from": 9.0,
                            "hour_to": 17.0,
                        }
                    )
                    for day_index, day_name in enumerate(
                        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
                    )
                ]
            }
        )
        cls.employee = cls.env["hr.employee"].create(
            {
                "name": "Test Employee",
                "resource_calendar_id": calendar.id,
                "parent_id": cls.manager.id,
            }
        )
        two_week_calendar = cls.env["resource.calendar"].create(
            {
                "name": "Test 2-week Calendar",
                "tz": "UTC",
                "two_weeks_calendar": True,
            }
        )
        two_week_calendar.attendance_ids.unlink()
        # Even week (week_type='0'): Mon–Fri, 5 days.
        # Odd week  (week_type='1'): Tue–Fri, 4 days (Monday off).
        two_week_calendar.write(
            {
                "attendance_ids": [
                    Command.create(
                        {
                            "name": f"Week 1 {day_name}",
                            "week_type": "0",
                            "dayofweek": str(day_index),
                            "hour_from": 9.0,
                            "hour_to": 17.0,
                        }
                    )
                    for day_index, day_name in enumerate(
                        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
                    )
                ]
                + [
                    Command.create(
                        {
                            "name": f"Week 2 {day_name}",
                            "week_type": "1",
                            "dayofweek": str(day_index),
                            "hour_from": 9.0,
                            "hour_to": 17.0,
                        }
                    )
                    for day_index, day_name in enumerate(
                        ["Tuesday", "Wednesday", "Thursday", "Friday"], start=1
                    )
                ]
            }
        )
        cls.employee_two_week = cls.env["hr.employee"].create(
            {
                "name": "Test Employee Two Week",
                "resource_calendar_id": two_week_calendar.id,
                "parent_id": cls.manager.id,
            }
        )
        cls.leave_type = cls.env["hr.leave.type"].create(
            {
                "name": "Test Leave",
                "leave_validation_type": "manager",
                "requires_allocation": "no",
                "time_type": "leave",
            }
        )

    def _make_public_holiday(self, holiday_date, name="Test Holiday"):
        """Create a country-agnostic public holiday on *holiday_date*.

        Searches for an existing hr.holidays.public record for the same year
        (without country) and reuses it, so multiple calls within one test
        method can share the same year record without hitting the uniqueness
        constraint.
        """
        HrHolidaysPublic = self.env["hr.holidays.public"].sudo()
        year_record = HrHolidaysPublic.search(
            [("year", "=", holiday_date.year), ("country_id", "=", False)], limit=1
        )
        if not year_record:
            year_record = HrHolidaysPublic.create({"year": holiday_date.year})
        return (
            self.env["hr.holidays.public.line"]
            .sudo()
            .create({"name": name, "date": holiday_date, "year_id": year_record.id})
        )

    def _make_validated_leave(self, employee, date_from, date_to):
        leave = (
            self.env["hr.leave"]
            .sudo()
            .create(
                {
                    "holiday_type": "employee",
                    "employee_id": employee.id,
                    "holiday_status_id": self.leave_type.id,
                    "date_from": date_from,
                    "date_to": date_to,
                }
            )
        )
        if leave.state == "draft":
            leave.sudo().action_confirm()
        if leave.state in ("confirm", "validate1"):
            leave.with_user(self.manager_user).action_validate()
        return leave
